// VPN Frontier v6.1.0 — i18n

var COUNTRIES_RU = {"AF":"Афганистан","AL":"Албания","DZ":"Алжир","AD":"Андорра","AO":"Ангола","AR":"Аргентина","AM":"Армения","AU":"Австралия","AT":"Австрия","AZ":"Азербайджан","BS":"Багамы","BH":"Бахрейн","BD":"Бангладеш","BB":"Барбадос","BY":"Беларусь","BE":"Бельгия","BZ":"Белиз","BJ":"Бенин","BT":"Бутан","BO":"Боливия","BA":"Босния и Герцеговина","BW":"Ботсвана","BR":"Бразилия","BN":"Бруней","BG":"Болгария","BF":"Буркина-Фасо","BI":"Бурунди","KH":"Камбоджа","CM":"Камерун","CA":"Канада","CF":"ЦАР","TD":"Чад","CL":"Чили","CN":"Китай","CO":"Колумбия","CD":"ДР Конго","CR":"Коста-Рика","HR":"Хорватия","CU":"Куба","CY":"Кипр","CZ":"Чехия","DK":"Дания","DJ":"Джибути","DO":"Доминикана","EC":"Эквадор","EG":"Египет","SV":"Сальвадор","EE":"Эстония","ET":"Эфиопия","FI":"Финляндия","FR":"Франция","GA":"Габон","GM":"Гамбия","GE":"Грузия","DE":"Германия","GH":"Гана","GR":"Греция","GT":"Гватемала","GN":"Гвинея","HT":"Гаити","HN":"Гондурас","HK":"Гонконг","HU":"Венгрия","IS":"Исландия","IN":"Индия","ID":"Индонезия","IR":"Иран","IQ":"Ирак","IE":"Ирландия","IL":"Израиль","IT":"Италия","JM":"Ямайка","JP":"Япония","JO":"Иордания","KZ":"Казахстан","KE":"Кения","KP":"КНДР","KR":"Южная Корея","KW":"Кувейт","KG":"Киргизия","LA":"Лаос","LV":"Латвия","LB":"Ливан","LY":"Ливия","LI":"Лихтенштейн","LT":"Литва","LU":"Люксембург","MO":"Макао","MG":"Мадагаскар","MY":"Малайзия","MV":"Мальдивы","ML":"Мали","MT":"Мальта","MX":"Мексика","MD":"Молдова","MC":"Монако","MN":"Монголия","ME":"Черногория","MA":"Марокко","MZ":"Мозамбик","MM":"Мьянма","NA":"Намибия","NP":"Непал","NL":"Нидерланды","NZ":"Новая Зеландия","NI":"Никарагуа","NE":"Нигер","NG":"Нигерия","MK":"Северная Македония","NO":"Норвегия","OM":"Оман","PK":"Пакистан","PA":"Панама","PY":"Парагвай","PE":"Перу","PH":"Филиппины","PL":"Польша","PT":"Португалия","QA":"Катар","RO":"Румыния","RU":"Россия","RW":"Руанда","SA":"Саудовская Аравия","SN":"Сенегал","RS":"Сербия","SG":"Сингапур","SK":"Словакия","SI":"Словения","SO":"Сомали","ZA":"ЮАР","ES":"Испания","LK":"Шри-Ланка","SD":"Судан","SE":"Швеция","CH":"Швейцария","SY":"Сирия","TW":"Тайвань","TJ":"Таджикистан","TZ":"Танзания","TH":"Таиланд","TG":"Того","TN":"Тунис","TR":"Турция","TM":"Туркменистан","UA":"Украина","AE":"ОАЭ","GB":"Великобритания","US":"США","UY":"Уругвай","UZ":"Узбекистан","VE":"Венесуэла","VN":"Вьетнам","YE":"Йемен","ZM":"Замбия","ZW":"Зимбабве"};

var COUNTRIES_EN = {"AF":"Afghanistan","AL":"Albania","DZ":"Algeria","AD":"Andorra","AO":"Angola","AR":"Argentina","AM":"Armenia","AU":"Australia","AT":"Austria","AZ":"Azerbaijan","BS":"Bahamas","BH":"Bahrain","BD":"Bangladesh","BB":"Barbados","BY":"Belarus","BE":"Belgium","BZ":"Belize","BJ":"Benin","BT":"Bhutan","BO":"Bolivia","BA":"Bosnia and Herzegovina","BW":"Botswana","BR":"Brazil","BN":"Brunei","BG":"Bulgaria","BF":"Burkina Faso","BI":"Burundi","KH":"Cambodia","CM":"Cameroon","CA":"Canada","CF":"Central African Republic","TD":"Chad","CL":"Chile","CN":"China","CO":"Colombia","CD":"DR Congo","CR":"Costa Rica","HR":"Croatia","CU":"Cuba","CY":"Cyprus","CZ":"Czechia","DK":"Denmark","DJ":"Djibouti","DO":"Dominican Republic","EC":"Ecuador","EG":"Egypt","SV":"El Salvador","EE":"Estonia","ET":"Ethiopia","FI":"Finland","FR":"France","GA":"Gabon","GM":"Gambia","GE":"Georgia","DE":"Germany","GH":"Ghana","GR":"Greece","GT":"Guatemala","GN":"Guinea","HT":"Haiti","HN":"Honduras","HK":"Hong Kong","HU":"Hungary","IS":"Iceland","IN":"India","ID":"Indonesia","IR":"Iran","IQ":"Iraq","IE":"Ireland","IL":"Israel","IT":"Italy","JM":"Jamaica","JP":"Japan","JO":"Jordan","KZ":"Kazakhstan","KE":"Kenya","KP":"North Korea","KR":"South Korea","KW":"Kuwait","KG":"Kyrgyzstan","LA":"Laos","LV":"Latvia","LB":"Lebanon","LY":"Libya","LI":"Liechtenstein","LT":"Lithuania","LU":"Luxembourg","MO":"Macau","MG":"Madagascar","MY":"Malaysia","MV":"Maldives","ML":"Mali","MT":"Malta","MX":"Mexico","MD":"Moldova","MC":"Monaco","MN":"Mongolia","ME":"Montenegro","MA":"Morocco","MZ":"Mozambique","MM":"Myanmar","NA":"Namibia","NP":"Nepal","NL":"Netherlands","NZ":"New Zealand","NI":"Nicaragua","NE":"Niger","NG":"Nigeria","MK":"North Macedonia","NO":"Norway","OM":"Oman","PK":"Pakistan","PA":"Panama","PY":"Paraguay","PE":"Peru","PH":"Philippines","PL":"Poland","PT":"Portugal","QA":"Qatar","RO":"Romania","RU":"Russia","RW":"Rwanda","SA":"Saudi Arabia","SN":"Senegal","RS":"Serbia","SG":"Singapore","SK":"Slovakia","SI":"Slovenia","SO":"Somalia","ZA":"South Africa","ES":"Spain","LK":"Sri Lanka","SD":"Sudan","SE":"Sweden","CH":"Switzerland","SY":"Syria","TW":"Taiwan","TJ":"Tajikistan","TZ":"Tanzania","TH":"Thailand","TG":"Togo","TN":"Tunisia","TR":"Turkey","TM":"Turkmenistan","UA":"Ukraine","AE":"UAE","GB":"United Kingdom","US":"United States","UY":"Uruguay","UZ":"Uzbekistan","VE":"Venezuela","VN":"Vietnam","YE":"Yemen","ZM":"Zambia","ZW":"Zimbabwe"};

function countryFlag(code) {
  if (!code || code.length !== 2) return "";
  return String.fromCodePoint(0x1F1E6 + code.charCodeAt(0) - 65, 0x1F1E6 + code.charCodeAt(1) - 65);
}

function countryName(code) {
  var map = currentLang === "ru" ? COUNTRIES_RU : COUNTRIES_EN;
  return map[code] || code;
}

function countryFull(code) {
  if (!code) return "—";
  return countryFlag(code) + " " + countryName(code) + " (" + code + ")";
}

var STRINGS = {
  ru: {
    "bl.title": "Доступ заблокирован для вашей безопасности",
    "bl.sub": "VPN Frontier перехватил запрос до того, как он покинул ваш браузер. Ваш IP за пределами России — доступ к российским ресурсам ограничен. Не забывайте отключать VPN, когда он не нужен.",
    "bl.url_label": "Заблокированный адрес",
    "bl.url_unknown": "URL не определен",
    "bl.check_btn": "🔄 Проверить IP",
    "bl.checking": "⏳ Проверка…",
    "bl.go_btn": "→ Перейти на сайт",
    "bl.going": "⏳ Переход…",
    "bl.back": "← Назад",
    "bl.close": "Закрыть вкладку",
    "bl.ok_title": "✅ IP российский",
    "bl.ok_detail": "Ваш IP подтвержден как реальный российский. Доступ разрешен.",
    "bl.vpn_title": "💡 Российский VPN",
    "bl.vpn_detail": "Обнаружен российский VPN. Доступ разрешен, но VPN лучше не включать без необходимости.",
    "bl.fail_title": "❌ IP иностранный",
    "bl.fail_detail": "Страна: {country}. Доступ заблокирован.",
    "bl.unk_title": "❌ Не удалось определить",
    "bl.unk_detail": "Доступ заблокирован по умолчанию.",
    "bl.err_title": "Ошибка",
    "bl.err_detail": "Не удалось проверить IP.",
    "bl.warn_vpn_h": "VPN включен? Отключите его",
    "bl.warn_vpn_p": "Доступ к российским доменам с иностранным IP запрещен. Запрос заблокирован на уровне браузера — данные не отправлены. Отключите VPN и обновите страницу.",
    "bl.warn_why_h": "Зачем это нужно?",
    "bl.warn_why_p": "VPN Frontier ограничивает доступ к российским ресурсам, когда вы за рубежом. Это касается всех зон — .ru, .рф, .su и пользовательских.",
    "bl.zones": "Заблокированные зоны",
    "p.status": "Статус", "p.country": "Страна", "p.ip": "IP", "p.isp": "ISP",
    "p.reason": "Причина", "p.checked": "Проверка", "p.error": "Ошибка",
    "p.badge_block": "БЛОКИРОВКА", "p.badge_open": "ОТКРЫТО", "p.badge_vpn": "VPN ⚠️",
    "p.badge_pause": "ПАУЗА", "p.badge_check": "ПРОВЕРКА…",
    "p.vpn_warn": "💡 VPN — {reason}. Доступ разрешен, но VPN лучше не включать без необходимости.",
    "p.sec_zones": "Заблокированные зоны", "p.sec_wl": "Белый список",
    "p.sec_hist": "История блокировок", "p.sec_ie": "Импорт / Экспорт",
    "p.sec_providers": "Сервисы проверки IP", "p.sec_settings": "Настройки проверки",
    "p.add": "+ Добавить", "p.ph_tld": ".by, .kz, .ua …", "p.ph_wl": "translate.yandex.ru", "p.empty": "Пусто",
    "p.btn_check": "🔄 Проверить IP", "p.btn_pause": "⏸ Пауза", "p.btn_resume": "▶ Возобновить",
    "p.export": "📋 Экспорт", "p.import": "📥 Импорт", "p.ie_ph": "JSON данные...",
    "p.ie_copied": "✅ Скопировано", "p.ie_manual": "📋 Скопируйте из поля",
    "p.ie_ok": "✅ Импортировано", "p.ie_err": "❌ Ошибка: ", "p.ie_empty": "❌ Вставьте JSON",
    "p.hist_empty": "Нет записей", "p.hist_clear": "🗑 Очистить", "p.hist_cleared": "Очищено",
    "p.hist_more": "...и еще {n}",
    "p.ago_s": "{n}с", "p.ago_m": "{n}м", "p.ago_h": "{n}ч",
    "p.freq_label": "Интервал проверки",
    "p.freq_5": "5 мин", "p.freq_10": "10 мин", "p.freq_15": "15 мин", "p.freq_30": "30 мин", "p.freq_60": "1 час",
    "p.cond_label": "Проверять IP при",
    "p.cond_nav": "Заход на заблокированный сайт",
    "p.cond_tab": "Переключение вкладки",
    "p.cond_timer": "По таймеру (интервал выше)",
    "p.cond_startup": "Запуск браузера",
    "p.cond_wake": "Выход из спящего режима",
    "p.cond_focus": "Возврат в окно браузера",
    "p.sound_label": "Звук при блокировке",
    "p.sound_on": "Включен",
    "p.sound_off": "Выключен",
    "p.open_settings": "⚙ Настройки",
    "o.title": "VPN Frontier — Настройки",
    "o.sec_general": "Основные настройки",
    "o.sec_providers": "Сервисы проверки IP",
    "o.sec_zones": "Заблокированные зоны",
    "o.sec_wl": "Белый список",
    "o.sec_stats": "Статистика блокировок",
    "o.sec_ie": "Импорт / Экспорт настроек",
    "o.sec_about": "О расширении",
    "o.sec_privacy": "Политика конфиденциальности",
    "o.stats_today": "Сегодня",
    "o.stats_week": "За 7 дней",
    "o.stats_total": "Всего",
    "o.stats_top": "Топ заблокированных доменов",
    "o.stats_chart": "По дням",
    "o.stats_no_data": "Нет данных",
    "o.stats_reset": "Сбросить статистику",
    "o.about_text": "VPN Frontier — расширение для Chrome, которое блокирует доступ к российским доменным зонам, если ваш IP находится за пределами России. Работает на уровне браузера — запросы не отправляются на сервер.",
    "o.privacy_text": "VPN Frontier не собирает, не хранит и не передает ваши персональные данные. IP-адрес проверяется через сторонние API исключительно для определения страны. Результаты хранятся локально в вашем браузере. Расширение не отправляет никаких данных на внешние серверы, кроме запросов к выбранным сервисам проверки IP. История блокировок хранится только на вашем устройстве.",
    "o.saved": "✅ Сохранено",
    "p.prov_active": "Используется", "p.prov_inactive": "Отключен",
    "n.vpn_title": "⚠️ Российский VPN", "n.vpn_msg": "{reason}.\nVPN лучше не включать без необходимости.",
    "n.country_title": "🌍 Страна IP изменилась", "n.country_msg": "{from} → {to}. {status}",
    "n.block_on": "Блокировка.", "n.block_off": "Доступ разрешен.",
    "n.tld_exists": "Уже в списке", "n.tld_added": "✅ Зона .{tld} добавлена",
    "n.wl_added": "✅ {domain} в белом списке",
    "ctx.block": "Заблокировать зону этого сайта", "ctx.wl": "Добавить в белый список",
  },
  en: {
    "bl.title": "Access blocked for your security",
    "bl.sub": "VPN Frontier intercepted the request before it left your browser. Your IP is outside Russia — access to Russian resources is restricted. Remember to turn off your VPN when you don't need it.",
    "bl.url_label": "Blocked address",
    "bl.url_unknown": "URL not determined",
    "bl.check_btn": "🔄 Check IP",
    "bl.checking": "⏳ Checking…",
    "bl.go_btn": "→ Go to site",
    "bl.going": "⏳ Redirecting…",
    "bl.back": "← Back",
    "bl.close": "Close tab",
    "bl.ok_title": "✅ Russian IP",
    "bl.ok_detail": "Your IP is confirmed as a real Russian IP. Access granted.",
    "bl.vpn_title": "💡 Russian VPN",
    "bl.vpn_detail": "Russian VPN detected. Access granted, but consider turning off your VPN.",
    "bl.fail_title": "❌ Foreign IP",
    "bl.fail_detail": "Country: {country}. Access blocked.",
    "bl.unk_title": "❌ Could not determine",
    "bl.unk_detail": "Access blocked by default.",
    "bl.err_title": "Error",
    "bl.err_detail": "Failed to check IP.",
    "bl.warn_vpn_h": "VPN on? Turn it off",
    "bl.warn_vpn_p": "Access to Russian domains from a foreign IP is prohibited. Request blocked at browser level — no data sent. Disconnect VPN and refresh.",
    "bl.warn_why_h": "Why is this needed?",
    "bl.warn_why_p": "VPN Frontier restricts access to Russian resources when abroad. Applies to all zones — .ru, .рф, .su and custom domains.",
    "bl.zones": "Blocked zones",
    "p.status": "Status", "p.country": "Country", "p.ip": "IP", "p.isp": "ISP",
    "p.reason": "Reason", "p.checked": "Checked", "p.error": "Error",
    "p.badge_block": "BLOCKING", "p.badge_open": "OPEN", "p.badge_vpn": "VPN ⚠️",
    "p.badge_pause": "PAUSED", "p.badge_check": "CHECKING…",
    "p.vpn_warn": "💡 VPN — {reason}. Access allowed, but consider turning off VPN.",
    "p.sec_zones": "Blocked zones", "p.sec_wl": "Whitelist",
    "p.sec_hist": "Block history", "p.sec_ie": "Import / Export",
    "p.sec_providers": "IP check services", "p.sec_settings": "Check settings",
    "p.add": "+ Add", "p.ph_tld": ".by, .kz, .ua …", "p.ph_wl": "translate.yandex.ru", "p.empty": "Empty",
    "p.btn_check": "🔄 Check IP", "p.btn_pause": "⏸ Pause", "p.btn_resume": "▶ Resume",
    "p.export": "📋 Export", "p.import": "📥 Import", "p.ie_ph": "JSON data...",
    "p.ie_copied": "✅ Copied", "p.ie_manual": "📋 Copy from field",
    "p.ie_ok": "✅ Imported", "p.ie_err": "❌ Error: ", "p.ie_empty": "❌ Paste JSON",
    "p.hist_empty": "No records", "p.hist_clear": "🗑 Clear", "p.hist_cleared": "Cleared",
    "p.hist_more": "...and {n} more",
    "p.ago_s": "{n}s", "p.ago_m": "{n}m", "p.ago_h": "{n}h",
    "p.freq_label": "Check interval",
    "p.freq_5": "5 min", "p.freq_10": "10 min", "p.freq_15": "15 min", "p.freq_30": "30 min", "p.freq_60": "1 hour",
    "p.cond_label": "Check IP on",
    "p.cond_nav": "Visit to a blocked site",
    "p.cond_tab": "Tab switch",
    "p.cond_timer": "Timer (interval above)",
    "p.cond_startup": "Browser startup",
    "p.cond_wake": "Wake from sleep",
    "p.cond_focus": "Return to browser window",
    "p.sound_label": "Sound on block",
    "p.sound_on": "On",
    "p.sound_off": "Off",
    "p.open_settings": "⚙ Settings",
    "o.title": "VPN Frontier — Settings",
    "o.sec_general": "General settings",
    "o.sec_providers": "IP check services",
    "o.sec_zones": "Blocked zones",
    "o.sec_wl": "Whitelist",
    "o.sec_stats": "Block statistics",
    "o.sec_ie": "Import / Export settings",
    "o.sec_about": "About",
    "o.sec_privacy": "Privacy policy",
    "o.stats_today": "Today",
    "o.stats_week": "Last 7 days",
    "o.stats_total": "Total",
    "o.stats_top": "Top blocked domains",
    "o.stats_chart": "By day",
    "o.stats_no_data": "No data",
    "o.stats_reset": "Reset statistics",
    "o.about_text": "VPN Frontier is a Chrome extension that blocks access to Russian domain zones when your IP is outside Russia. Works at the browser level — requests are never sent to the server.",
    "o.privacy_text": "VPN Frontier does not collect, store, or transmit your personal data. Your IP address is checked through third-party APIs solely to determine your country. Results are stored locally in your browser. The extension does not send any data to external servers except requests to the selected IP check services. Block history is stored only on your device.",
    "o.saved": "✅ Saved",
    "p.prov_active": "Active", "p.prov_inactive": "Disabled",
    "n.vpn_title": "⚠️ Russian VPN", "n.vpn_msg": "{reason}.\nConsider turning off VPN.",
    "n.country_title": "🌍 IP country changed", "n.country_msg": "{from} → {to}. {status}",
    "n.block_on": "Blocking activated.", "n.block_off": "Access granted.",
    "n.tld_exists": "Already listed", "n.tld_added": "✅ Zone .{tld} added",
    "n.wl_added": "✅ {domain} whitelisted",
    "ctx.block": "Block this site's zone", "ctx.wl": "Add to whitelist",
  }
};

var currentLang = "ru";
function t(key, vars) {
  var s = (STRINGS[currentLang] && STRINGS[currentLang][key]) || STRINGS.ru[key] || key;
  if (vars) Object.keys(vars).forEach(function(k) { s = s.replace("{" + k + "}", vars[k]); });
  return s;
}
function setLang(lang) { currentLang = lang; chrome.storage.sync.set({ lang: lang }); }
function loadLang(cb) { chrome.storage.sync.get({ lang: "ru" }, function(d) { currentLang = d.lang; if (cb) cb(currentLang); }); }
